SELECT S.SNAME, COUNT(P.PNAME) AS Total_Parts_Supplied
FROM SUPPLIERS S, PARTS P, CATALOG C
WHERE S.SID = C.SID AND P.PID = C.PID
GROUP BY S.SNAME;

SELECT S.SNAME, COUNT(P.PNAME) AS Total_Parts_Supplied
FROM SUPPLIERS S, PARTS P, CATALOG C
WHERE S.SID = C.SID AND P.PID = C.PID
GROUP BY S.SNAME
HAVING COUNT(P.PNAME) >= 3;

SELECT S.SNAME, COUNT(P.PNAME) AS Total_Parts_Supplied
FROM SUPPLIERS S, PARTS P, CATALOG C
WHERE S.SID = C.SID AND P.PID = C.PID AND P.COLOR IN ('Green')
GROUP BY S.SNAME;

SELECT S.SNAME, MAX(C.COST) AS Highest_Cost_Of_Product
FROM SUPPLIERS S, PARTS P, CATALOG C
WHERE S.SID = C.SID AND P.PID = C.PID AND P.COLOR NOT IN ('Black', 'Cyan', 'Silver', 'Transluctent', 'Magenta')
GROUP BY S.SNAME;

SELECT DISTINCT S.SNAME, P.PNAME 
FROM SUPPLIERS S, PARTS P, CATALOG C
WHERE P.COLOR = 'Green';

SELECT DISTINCT S.SNAME, P.PNAME
FROM SUPPLIERS S, PARTS P, CATALOG C
WHERE P.COLOR = 'Red';
